# Generated by Django 5.2.8 on 2025-11-22 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('fraud_detected', models.PositiveIntegerField(default=0)),
                ('safe_reports', models.PositiveIntegerField(default=0)),
                ('avg_risk_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Tendance Fraude',
                'verbose_name_plural': 'Tendances Fraude',
                'ordering': ['-date'],
            },
        ),
    ]
