# Generated by Django 5.2.8 on 2025-11-22 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description du message suspect')),
                ('phone_number', models.CharField(blank=True, help_text='+237XXXXXXXXX', max_length=13)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='reports/evidence/')),
                ('risk_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('fraud', 'Fraude détectée'), ('safe', 'Sûr'), ('review', 'En révision')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
